baseURL = "https://zayitsolutions.com/"
languageCode = "en-us"
title = "Zayit Solutions"
theme = "PaperMod"
paginate = 5

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowToc = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 20
